### ISSUE TITLE
Preview 6

### ISSUE THREAD

**Issue by AJB-Sharp** [danroth27/BlazingPizza#7]
Dan 

Since updating to preview 6, I get the following error:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.AspNetCore.Builder.IEndpointConventionBuilder Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithDisplayName(Microsoft.AspNetCore.Builder.IEndpointConventionBuilder, System.String)'.
  Source=Grpc.AspNetCore.Server
  StackTrace:
   at Grpc.AspNetCore.Server.Internal.GrpcServiceBinder`1.AddMethodCore(IMethod method, RequestDelegate requestDelegate, List`1 metadata)
   at Grpc.AspNetCore.Server.Internal.GrpcServiceBinder`1.AddMethod[TRequest,TResponse](Method`2 method, UnaryServerMethod`2 handler)
   at BlazingPizza.OrderStatusUpdates.PizzaOrderStatus.BindService(ServiceBinderBase serviceBinder, PizzaOrderStatusBase serviceImpl) in C:\Quote\Test\BlazingPizza-master\BlazingPizza-master\src\BlazingPizza\obj\Debug\netcoreapp3.0\PizzaorderstatusGrpc.cs:line 55

Have I inadvertently changes something or is it Preview 6 causing the problem.

Kind regards

Alan Bannister

**Comment by waelkdouh** [comment]
Any update on this issue?
